name: Deploy to Firebase Hosting
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "src/status-page/**"
      - ".github/workflows/firebase-hosting-merge.yml"

jobs:
  build_and_deploy:
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}
          token_format: "access_token"

      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            src/status-page

      - name: Prepare source files
        run: |
          mkdir mytmp
          mv src/status-page/* ./mytmp
          rm -rf ./src
          mv mytmp/* ./

      - name: Build app
        shell: bash
        run: npm ci && npm run build
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY}}
          VITE_FIREBASE_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ vars.GCP_PROJECT_ID }}.firebaseapp.com
          VITE_FIREBASE_STORAGE_BUCKET: ${{ vars.GCP_PROJECT_ID }}.firebasestorage.app
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}

      - name: Deploy to Firebase Hosting
        run: |
          /usr/local/bin/npx firebase-tools@latest deploy --only hosting:savemyfuse-admin --project ${{ vars.GCP_PROJECT_ID }} --json
